accounts/urls.py
from django.urls import path

from . import views


app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/",views.login_view, name="login"),
    path("logout/",views.logout_view, name="logout"),
]

djangomath/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mymath.urls")),
    path("accounts/", include("accounts.urls")),
]

mymath/urls.py
from django.urls import path, include

from . import views

app_name = "mymath"

urlpatterns = [
    path("", views.index, name="index"),
    path("exam/<int:exam_id>/<int:number>/", views.exam, name="exam"),    
    path("exam/<int:exam_id>/<int:number>/answer/", views.answer, name="answer"),
    path("exam/<int:exam_id>/result/", views.result, name="result"),
]

templates/base.html
<!DOCTYPE html>
<html lang="ja">

<!--django-bootstrap5をインストール済み-->
{% load django_bootstrap5 %}

{% load crispy_forms_tags %}

<head>
  {% load static %}
  
  <meta charset="UTF-8">
  
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap 5 の CDN -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  {% block extra_css %}
    <link rel="stylesheet" href="{% static 'mymath/css/style.css' %}">
  {% endblock %}<!--cssの追加-->
</head>

<body class="d-flex flex-column min-vh-100" style="background-color: rgb(252, 252, 250);">
  <!--ナビバー-->
  
  <nav class="navbar navbar-expand-lg text-white shadow-sm rounded-pill" style="background-color: rgb(57, 200, 179);">
    <div class="container d-flex justify-content-between align-items-center">
      <a class="navbar-brand fw-bold my-3 lh-sm hover-opacity" href="{% url 'mymath:index' %}">
        <h2 class="mb-0 text-white">MyMathStudy</h2>
        <h5 class="mb-0" style="color: #848484;">算数・数学の</h5>
        <h5 class="mb-0 text-white">学習サイト</h5>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse " id="navbarNav">
        {% if user.is_authenticated %}
        <ul class="navbar-nav" >
          <li><a class="nav-link text-white fw-bold hover-opacity" href="">リンク1</a></li>
          <li><a class="nav-link text-white fw-bold hover-opacity" href="">リンク2</a></li>
        </ul>
        <strong class="ms-auto">こんにちは、{{ user.username }}さん</strong> 
        {% endif %}
        <ul class="navbar-nav ms-auto mx-5">  
          {% if user.is_authenticated %}
          <li class="nav-item">
            <form method="post" action="{% url 'accounts:logout' %}" >
              {% csrf_token %}
              <button type="submit" class="btn btn-link nav-link fw-bold hover-opacity" style="background-color: #ffffff;">
                LogOut
              </button>
            </form>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="btn nav-link fw-bold hover-opacity mx-2" href="{% url 'accounts:signup' %}" style="background-color: #ffffff;">SignUp</a>
          </li>
          <li class="nav-item">
            <a class="btn btn-link nav-link fw-bold hover-opacity mx-2" href="{% url 'accounts:login' %}" style="background-color: aliceblue;">LogIn</a>
          </li>
          {% endif %}
      </ul>
      
      
      
      </div>
    </div>
  </nav>
  
  
  

<h2 class="text-center card py-2" style="background-color: #f3f5f6;"> 
{% block header %}{% endblock %}
</h2>
<!-- messages を表示 -->
<div class="container my-2">
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}
</div>



<div class="my-2" style="background-color: #f1f5f6;">
{% block content %}

{% endblock %}
</div>   
  

<!-- フッター -->
   <footer class="py-5 container-fluid fw-bold mt-auto" style="background-color: #959595;">
    <div class="text-center">Copyright &copy;MyMathStudy 2025</div>
   </footer>  
  


</body>

templates/base_before.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap 5 の CDN -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body class="bg-light">
    <!-- ヘッダー -->
    <header class="mb-4 text-center bg-primary bg-opacity-50">
      {% block head %}{% endblock %}
    <!--ナビゲーション-->
    <nav class="navbar navbar-expand-lg  navbar-dark bg-primary-subtle shadow-sm">
      <div class="container d-flex justify-content-between align-items-center">
      <a class="navbar-brand fw-bold" href="{% url 'mymath:index' %}"><h1>MyMathStudy</h1><h5>算数・数学の学習サイト</h5></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text me-3">
              ようこそ、<strong>{{ user.username }}</strong> さん
            </span>
          </li>
        {% else %}
          <li class="nav-item">
              <span class="navbar-text me-3">
                ようこそ、ゲスト さん
              </span>
          </li> 
        {% endif %}
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
            
            <li class="nav-item">
              <a class="nav-link active" href="#">あなたのページ</a>
            </li>         
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'accounts:logout' %}">ログアウト</a>
            </li>
          {% else %}
            
        
            
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">登録</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">ログイン</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  
  
  <div class="container py-2 px-2">
    {% if messages %}
    <div class="container mt-3">
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
    </div>
    {% endif %}


  </div>
    </header>
    
    {% block contents %}{% endblock %}
    
  <!-- フッター -->
   <footer class="py-5 bg-black bg-opacity-75 text-white">
    <div class="text-center">Copyright &copy;MyMathStudy 2025</div>
   </footer>
  
  

</div>
</body>
</html>